DROP SCHEMA IF EXISTS enterprise CASCADE;
CREATE SCHEMA enterprise AUTHORIZATION postgres
CREATE TABLE enterprise(
    enterprise_id VARCHAR(120) PRIMARY KEY,
    owner_user_id VARCHAR(255) NOT NULL,
    logo_img VARCHAR(255) NOT NULL,
    banner_img VARCHAR(255) NOT NULL,
    website VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(21) NOT NULL,
    address_id UUID NOT NULL,
    industry_id INTEGER NOT NULL,
    created_at VARCHAR(255) NOT NULL,
    updated_at VARCHAR(255) NOT NULL,
    foundation_date VARCHAR(255) NOT NULL
)
CREATE TABLE employee(
    employee_id UUID PRIMARY KEY NOT NULL,
    enterprise_id VARCHAR(120) NOT NULL,
	user_id VARCHAR(255) NOT NULL,
    hiring_date VARCHAR(255) NOT NULL,
    approved_hiring BOOLEAN NOT NULL,
    approved_hiring_at VARCHAR(255) NOT NULL,
    job_position VARCHAR(255) NOT NULL
)
CREATE TABLE industry(
    industry_id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE CHAT (
    ID  TEXT PRIMARY KEY
);
CREATE TABLE CHAT_REPLY(
    ID UUID PRIMARY KEY,
    CHAT_ID TEXT NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(255) NOT NULL,
    SEEN BOOLEAN NOT NULL,
    CREATED_AT VARCHAR(255) NOT NULL,
    UPDATED_AT VARCHAR(255) NOT NULL
);
BEGIN;
INSERT INTO industry (industry_id, name) VALUES
(1, 'Software Development'),
(2, 'Food Service'),
(3, 'Retail'),
(4, 'Automotive Manufacturing'),
(5, 'Construction'),
(6, 'Healthcare'),
(7, 'Education'),
(8, 'Financial Services'),
(9, 'Marketing & Advertising'),
(10, 'Telecommunications'),
(11, 'Media & Entertainment'),
(12, 'Travel & Tourism'),
(13, 'Logistics & Transportation'),
(14, 'Real Estate'),
(15, 'Government'),
(16, 'Energy'),
(17, 'Manufacturing'),
(18, 'Mining'),
(19, 'Agriculture'),
(20, 'Forestry'),
(21, 'Fishing'),
(22, 'Chemicals'),
(23, 'Pharmaceuticals'),
(24, 'Biotechnology'),
(25, 'Aerospace'),
(26, 'Defense'),
(27, 'Retail Trade'),
(28, 'Wholesale Trade'),
(29, 'Computer Hardware'),
(30, 'Semiconductors'),
(31, 'Electronics'),
(32, 'Machinery'),
(33, 'Furniture'),
(34, 'Appliances'),
(35, 'Toys & Games'),
(36, 'Sporting Goods'),
(37, 'Apparel'),
(38, 'Footwear'),
(39, 'Textiles'),
(40, 'Paper Products'),
(41, 'Printing'),
(42, 'Packaging'),
(43, 'Waste Management'),
(44, 'Recycling'),
(45, 'Environmental Services'),
(46, 'Accounting'),
(47, 'Law'),
(48, 'Human Resources'),
(49, 'Management Consulting'),
(50, 'Security'),
(51, 'Facilities Management'),
(52, 'Customer Service'),
(53, 'Sales'),
(54, 'Public Relations'),
(55, 'Non-Profit'),
(56, 'Arts & Entertainment'),
(57, 'Music'),
(58, 'Movies & Film'),
(59, 'Theater'),
(60, 'Literature'),
(61, 'Visual Arts'),
(62, 'Performing Arts'),
(63, 'Sports'),
(64, 'Recreation'),
(65, 'Gambling & Casinos'),
(66, 'Hotels & Resorts'),
(67, 'Restaurants'),
(68, 'Airlines'),
(69, 'Airports'),
(70, 'Shipping'),
(71, 'Trucking'),
(72, 'Railroads'),
(73, 'Postal Services'),
(74, 'Delivery Services'),
(75, 'Warehousing'),
(76, 'Real Estate Development'),
(77, 'Property Management'),
(78, 'Rental Services'),
(79, 'Oil & Gas'),
(80, 'Coal'),
(81, 'Electricity'),
(82, 'Renewables'),
(83, 'Nuclear Power'),
(84, 'Mining & Metals'),
(85, 'Gold'),
(86, 'Copper'),
(87, 'Iron Ore'),
(88, 'Coal Mining'),
(89, 'Farming'),
(90, 'Livestock'),
(91, 'Dairy'),
(92, 'Poultry'),
(93, 'Fishing & Seafood'),
(94, 'Forestry & Logging'),
(95, 'Wood Products'),
(96, 'Paper & Pulp'),
(97, 'Chemicals & Materials'),
(98, 'Plastics'),
(99, 'Rubber'),
(100, 'Pharmaceuticals & Biotech'),
(101, 'Medical Devices'),
(102, 'Aerospace & Defense'),
(103, 'Airplanes'),
(104, 'Satellites'),
(105, 'Weapons'),
(106, 'Consumer Goods'),
(107, 'Food & Beverages'),
(108, 'Household Goods'),
(109, 'Personal Care'),
(110, 'Wholesale Trade'),
(111, 'Information Technology'),
(112, 'Telecommunications'),
(113, 'Media & Entertainment'),
(114, 'Financial Services'),
(115, 'Insurance'),
(116, 'Banking'),
(117, 'Investment Banking'),
(118, 'Real Estate'),
(119, 'Professional Services'),
(120, 'Accounting'),
(121, 'Law'),
(122, 'Consulting'),
(123, 'Human Resources'),
(124, 'Business Services'),
(125, 'Marketing & Advertising'),
(126, 'Security'),
(127, 'Facilities Management'),
(128, 'Transportation & Logistics'),
(129, 'Shipping'),
(130, 'Airlines'),
(131, 'Trucking'),
(132, 'Railroads'),
(133, 'Delivery Services'),
(134, 'Warehousing'),
(135, 'Rental & Leasing'),
(136, 'Management Consulting'),
(137, 'Public Relations'),
(138, 'Non-Profit'),
(139, 'Arts & Entertainment'),
(140, 'Music'),
(141, 'Movies & Film'),
(142, 'Theater'),
(143, 'Literature'),
(144, 'Visual Arts'),
(145, 'Performing Arts'),
(146, 'Sports'),
(147, 'Recreation'),
(148, 'Gambling & Casinos'),
(149, 'Hotels & Resorts'),
(150, 'Restaurants'),
(151, 'Bars & Nightclubs'),
(152, 'Travel Agencies'),
(153, 'Tourism Operators'),
(154, 'Airlines'),
(155, 'Airports'),
(156, 'Cruise Lines'),
(157, 'Car Rental'),
(158, 'Hospitality'),
(159, 'Timesharing'),
(160, 'Logistics & Transportation'),
(161, 'Freight Forwarding'),
(162, 'Supply Chain Management'),
(163, 'Warehousing & Distribution'),
(164, 'Postal Services'),
(165, 'Courier Services'),
(166, 'Trucking & Transportation'),
(167, 'Shipping & Freight'),
(168, 'Maritime'),
(169, 'Railroad Transportation'),
(170, 'Real Estate'),
(171, 'Real Estate Investment Trusts (REITs)'),
(172, 'Property Management'),
(173, 'Commercial Real Estate'),
(174, 'Residential Real Estate'),
(175, 'Real Estate Development'),
(176, 'Construction'),
(177, 'Building Materials'),
(178, 'Civil Engineering'),
(179, 'Electrical Engineering'),
(180, 'Mechanical Engineering'),
(181, 'Architecture'),
(182, 'Interior Design'),
(183, 'Facilities Management'),
(184, 'Property Maintenance'),
(185, 'Mining & Metals'),
(186, 'Gold Mining'),
(187, 'Copper Mining'),
(188, 'Iron Ore Mining'),
(189, 'Coal Mining'),
(190, 'Oil & Gas'),
(191, 'Exploration & Production'),
(192, 'Refining & Marketing'),
(193, 'Oilfield Services'),
(194, 'Energy'),
(195, 'Electricity Generation'),
(196, 'Renewable Energy'),
(197, 'Nuclear Power'),
(198, 'Utilities'),
(199, 'Forestry & Logging'),
(200, 'Wood Products');
END;