DROP SCHEMA IF EXISTS complaint CASCADE;
CREATE SCHEMA complaint AUTHORIZATION postgres 
CREATE TABLE complaint(
    id UUID PRIMARY KEY NOT NULL,
    author_id UUID NOT NULL,
    receiver_id UUID NOT NULL,
    status VARCHAR(15) NOT NULL,
    title VARCHAR(80),
    description VARCHAR(120),
    rating_id UUID,
    created_at VARCHAR(255) NOT NULL,
    updated_at VARCHAR(255) NOT NULL
)
CREATE TABLE recipients(
    id uuid PRIMARY KEY,
    is_enterprise BOOLEAN NOT NULL,
    subject_name VARCHAR(255) NOT NULL,
    subject_thumbnail VARCHAR(255) NOT NULL,
    subject_email VARCHAR(255) NOT NULL,
)
CREATE TABLE complaint_replies(
    id UUID PRIMARY KEY NOT NULL,
    complaint_id UUID NOT NULL,
    author_id UUID NOT NULL,
    body VARCHAR(250) NOT NULL,
    is_read BOOLEAN NOT NULL,
    read_at VARCHAR(255) NOT NULL,
    created_at VARCHAR(255) NOT NULL,
    updated_at VARCHAR(255) NOT NULL,
)
CREATE TABLE ratings(
    id UUID PRIMARY KEY,
    rating INTEGER,
    comment VARCHAR(250)
)

CREATE TABLE COMPLAINT_DATA(
    ID UUID PRIMARY KEY,
    OWNER_ID UUID NOT NULL,
    COMPLAINT_ID UUID NOT NULL,
    OCCURRED_ON VARCHAR(255) NOT NULL,
    DATA_TYPE VARCHAR(10) NOT NULL,
)

CREATE TABLE COMPLAINT_REVIEWS(
    ID UUID PRIMARY KEY,
    ATTENTION_BY_ID UUID NOT NULL,
    TRIGGERED_BY_ID UUID NOT NULL,
    RATED_BY_ID UUID NOT NULL,
    COMPLAINT_ID UUID NOT NULL,
    COMPLAINT_TITLE VARCHAR(255) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    OCCURRED_ON VARCHAR(255) NOT NULL
)