DROP SCHEMA IF EXISTS feedback CASCADE;
CREATE TABLE feedback(
    ID UUID PRIMARY KEY,
    ENTERPRISE_ID VARCHAR(255) NOT NULL,
    COMPLAINT_ID UUID NOT NULL,
    REVIEWED_ID VARCHAR(255) NOT NULL,
)
CREATE TABLE feedback_reply_review(
    ID UUID PRIMARY KEY,
    FEEDBACK_ID UUID NOT NULL,
    COLOR VARCHAR(255) NOT NULL,
)
CREATE TABLE feedback_reviews(
    ID UUID PRIMARY KEY,
    REVIEWER_ID UUID NOT NULL,
    REVIEWED_AT VARCHAR(255) NOT NULL,
    REVIEW_COMMENT VARCHAR(255) NOT NULL
)
CREATE TABLE feedback_replies(
    ID UUID PRIMARY KEY,
    REPLY_REVIEW_ID UUID NOT NULL,
    REPLY_ID UUID NOT NULL,
)
CREATE TABLE feedback_answers(
    ID UUID PRIMARY KEY,
    FEEDBACK_ID UUID NOT NULL,
    SENDER_ID VARCHAR(255) NOT NULL,
    ANSWER_BODY VARCHAR(255) NOT NULL,
    CREATED_AT VARCHAR(255) NOT NULL,
    READ_STATUS BOOLEAN NOT NULL,
    READ_AT VARCHAR(255) NOT NULL,
    UPDATED_AT VARCHAR(255) NOT NULL,
    IS_ENTERPRISE BOOLEAN NOT NULL,
    ENTERPRISE_ID VARCHAR(255)
);