DROP SCHEMA IF EXISTS feedback CASCADE;
CREATE SCHEMA feedback AUTHORIZATION postgres
CREATE TABLE feedbacks(
    ID UUID PRIMARY KEY,
    FEEDBACK_ID UUID,
    REVIEWED_ID VARCHAR(255) NOT NULL,
    REPLY_SENDER_ID VARCHAR(255) NOT NULL,
    REPLY_SENDER_IMG VARCHAR(255) NOT NULL,
    REPLY_SENDER_NAME VARCHAR(255) NOT NULL,
    REPLY_BODY VARCHAR(255)     NOT NULL,
    REPLY_CREATED_AT VARCHAR(255) NOT NULL,
    REPLY_READ BOOLEAN,
    REPLY_READ_AT VARCHAR(255) NOT NULL,
    REPLY_UPDATED_AT VARCHAR(255) NOT NULL,
    REVIEWER_ID VARCHAR(255) NOT NULL,
    REVIEWER_IMG VARCHAR(255) NOT NULL,
    REVIEWER_NAME VARCHAR(255)   NOT NULL,
    REVIEWED_AT VARCHAR(255) NOT NULL,
    REVIEW_COMMENT VARCHAR(255) NOT NULL
) CREATE TABLE answers(
    ID UUID PRIMARY KEY,
    FEEDBACK_ID UUID NOT NULL,
    SENDER_ID VARCHAR(255) NOT NULL,
    SENDER_IMG VARCHAR(255) NOT NULL,
    SENDER_NAME VARCHAR(255) NOT NULL,
    ANSWER_BODY VARCHAR(255) NOT NULL,
    CREATED_AT VARCHAR(255) NOT NULL,
    READ BOOLEAN NOT NULL,
    READ_AT VARCHAR(255) NOT NULL,
    UPDATED_AT VARCHAR(255) NOT NULL
)