/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n  fragment CountryFragment on Country {\n    id\n    name\n  }\n": types.CountryFragmentFragmentDoc,
    "\n    mutation createEnterprise($input: CreateEnterprise!){\n        createEnterprise(input: $input){\n            name\n        }\n    }": types.CreateEnterpriseDocument,
    "\n    mutation createNewComplaintMutation($input: CreateNewComplaint!){\n        createNewComplaint(input:$input){\n            id\n            receiver{\n                id\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n\n        }\n    }": types.CreateNewComplaintMutationDocument,
    "\n    mutation CreateUserMutation(\n        $input: CreateUser!){\n            createUser(\n                input: $input\n            ){\n                userName\n            }\n    }": types.CreateUserMutationDocument,
    "\n    mutation describeComplaintMutation($input:DescribeComplaint!){\n        describeComplaint(input:$input){\n            id\n            receiver{\n                id\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }\n    ": types.DescribeComplaintMutationDocument,
    "\n    mutation sendComplaintMutation($input: SendComplaint!) {\n        sendComplaint(input:$input){\n            id\n            receiver{\n                id\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }": types.SendComplaintMutationDocument,
    "\n    query CitiesQuery($id: Int!){\n        cities(id:$id){\n            id\n            name\n            countryCode\n            latitude\n            longitude\n        }\n    }": types.CitiesQueryDocument,
    "\n    query ComplaintByIdQuery($id: String!){\n        complaintById(id:$id){\n            id\n            author{\n                id\n                subjectName\n                subjectThumbnail\n                isOnline\n                isEnterprise\n            }\n            receiver{\n                id\n                subjectName\n                subjectThumbnail\n                isOnline\n                isEnterprise\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                    subjectName\n                    subjectThumbnail\n                    isEnterprise\n                }\n                body\n                read\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }": types.ComplaintByIdQueryDocument,
    "\n    query complaintsByAuthorIdOrReceiverIdQuery($id: String!){\n        complaintsByAuthorOrReceiverId(id:$id){\n            id\n            author{\n                id\n                subjectName\n                subjectThumbnail\n            }\n            receiver{\n                id\n                subjectName\n                subjectThumbnail\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                    subjectName\n                    subjectThumbnail\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }": types.ComplaintsByAuthorIdOrReceiverIdQueryDocument,
    "\n    query complaintsInfoQuery($id: String!) {\n        complaintsInfo(id: $id) {\n            received {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n            resolved {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n            reviewed {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n            sent {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n        }\n    }": types.ComplaintsInfoQueryDocument,
    "\n    query Countries{\n        countries{\n            id\n            name\n            phoneCode\n        }\n    }": types.CountriesDocument,
    "\n    query CountryStatesQuery($id: Int!){\n        countryStates(id: $id) {\n            id\n            name\n        }\n    }": types.CountryStatesQueryDocument,
    "\n    query enterpriseByNameQuery($name: String!){\n        enterpriseByName(name:$name){\n            name\n            logoImg\n            bannerImg\n            website\n            email\n            phoneNumber\n            address {\n                country\n                countryState\n                city\n                }\n            industry\n            foundationDate\n            ownerId\n            employees {\n                id\n                enterpriseId\n                userId\n                user{\n                    userName\n                    person{\n                        profileImg\n                        email\n                        firstName\n                        lastName\n                        genre\n                        pronoun\n                        age\n                        phoneNumber\n                        address{\n                            country\n                            countryState\n                            city\n                        }\n                    }\n                    status\n                }\n                hiringDate\n                approvedHiring\n                approvedHiringAt\n                enterprisePosition\n            }\n        }\n    }": types.EnterpriseByNameQueryDocument,
    "\nquery EnterprisesByAuthenticatedUserQuery{\n    enterprisesByAuthenticatedUser{\n        enterprises{\n            authority{\n            authority\n            enterpriseId\n        }\n        enterprise{\n            name\n            logoImg\n            bannerImg\n            website\n            email\n            phoneNumber\n            address {\n                country\n                countryState\n                city\n                }\n            industry\n            foundationDate\n            ownerId\n        }\n        }\n        offices{\n            authority{\n            authority\n            enterpriseId\n        }\n        enterprise{\n            name\n            logoImg\n            bannerImg\n            website\n            email\n            phoneNumber\n            address {\n                country\n                countryState\n                city\n                }\n            industry\n            foundationDate\n            ownerId\n        }\n        }\n    }\n}\n": types.EnterprisesByAuthenticatedUserQueryDocument,
    "\n    query hiringInvitationsByAuthenticatedUserQuery{\n        hiringInvitationsByAuthenticatedUser{\n            eventId\n            enterpriseId\n            proposedPosition\n            ownerId\n            fullName\n            enterpriseEmail\n            enterprisePhone\n            enterpriseLogoImg\n            occurredOn\n            seen\n            status\n            reason\n        }\n    }": types.HiringInvitationsByAuthenticatedUserQueryDocument,
    "query industries{\n        industries{\n            id\n            name\n        }\n    }": types.IndustriesDocument,
    "\n    query recipientsByNameLikeQuery($term:String!){\n        recipientsByNameLike(term:$term){\n            id\n            subjectName\n            subjectThumbnail\n            isEnterprise\n        }\n    }\n": types.RecipientsByNameLikeQueryDocument,
    "\n    query User($id:String!){\n        userById(id:$id){\n                userName\n                person {\n                    profileImg\n                    email\n                    firstName\n                    lastName\n                    genre\n                    pronoun\n                    age\n                    phoneNumber\n                    address { \n                        country\n                        countryState\n                        city\n                        }\n                }\n                status\n        }\n    }": types.UserDocument,
    "\n    query UserDescriptor{\n        userDescriptor{\n            id\n            userName\n            fullName\n            profileImg\n            genre\n            pronoun\n            authorities{\n                enterpriseId\n                principal\n                authority\n            }\n        }\n    }": types.UserDescriptorDocument,
    "\n    query usersForHiringQuery($input: SearchWithPagination!) {\n        usersForHiring(input:$input){\n            users {\n                userName\n                person {\n                    profileImg\n                    email\n                    firstName\n                    lastName\n                    genre\n                    pronoun\n                    age\n                    phoneNumber\n                    address { country countryState city}\n                }\n                status\n            }\n            count\n            limit\n            offset\n            nextCursor\n            prevCursor\n        }\n    }": types.UsersForHiringQueryDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment CountryFragment on Country {\n    id\n    name\n  }\n"): (typeof documents)["\n  fragment CountryFragment on Country {\n    id\n    name\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createEnterprise($input: CreateEnterprise!){\n        createEnterprise(input: $input){\n            name\n        }\n    }"): (typeof documents)["\n    mutation createEnterprise($input: CreateEnterprise!){\n        createEnterprise(input: $input){\n            name\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createNewComplaintMutation($input: CreateNewComplaint!){\n        createNewComplaint(input:$input){\n            id\n            receiver{\n                id\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n\n        }\n    }"): (typeof documents)["\n    mutation createNewComplaintMutation($input: CreateNewComplaint!){\n        createNewComplaint(input:$input){\n            id\n            receiver{\n                id\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateUserMutation(\n        $input: CreateUser!){\n            createUser(\n                input: $input\n            ){\n                userName\n            }\n    }"): (typeof documents)["\n    mutation CreateUserMutation(\n        $input: CreateUser!){\n            createUser(\n                input: $input\n            ){\n                userName\n            }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation describeComplaintMutation($input:DescribeComplaint!){\n        describeComplaint(input:$input){\n            id\n            receiver{\n                id\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }\n    "): (typeof documents)["\n    mutation describeComplaintMutation($input:DescribeComplaint!){\n        describeComplaint(input:$input){\n            id\n            receiver{\n                id\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }\n    "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation sendComplaintMutation($input: SendComplaint!) {\n        sendComplaint(input:$input){\n            id\n            receiver{\n                id\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }"): (typeof documents)["\n    mutation sendComplaintMutation($input: SendComplaint!) {\n        sendComplaint(input:$input){\n            id\n            receiver{\n                id\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query CitiesQuery($id: Int!){\n        cities(id:$id){\n            id\n            name\n            countryCode\n            latitude\n            longitude\n        }\n    }"): (typeof documents)["\n    query CitiesQuery($id: Int!){\n        cities(id:$id){\n            id\n            name\n            countryCode\n            latitude\n            longitude\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ComplaintByIdQuery($id: String!){\n        complaintById(id:$id){\n            id\n            author{\n                id\n                subjectName\n                subjectThumbnail\n                isOnline\n                isEnterprise\n            }\n            receiver{\n                id\n                subjectName\n                subjectThumbnail\n                isOnline\n                isEnterprise\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                    subjectName\n                    subjectThumbnail\n                    isEnterprise\n                }\n                body\n                read\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }"): (typeof documents)["\n    query ComplaintByIdQuery($id: String!){\n        complaintById(id:$id){\n            id\n            author{\n                id\n                subjectName\n                subjectThumbnail\n                isOnline\n                isEnterprise\n            }\n            receiver{\n                id\n                subjectName\n                subjectThumbnail\n                isOnline\n                isEnterprise\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                    subjectName\n                    subjectThumbnail\n                    isEnterprise\n                }\n                body\n                read\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query complaintsByAuthorIdOrReceiverIdQuery($id: String!){\n        complaintsByAuthorOrReceiverId(id:$id){\n            id\n            author{\n                id\n                subjectName\n                subjectThumbnail\n            }\n            receiver{\n                id\n                subjectName\n                subjectThumbnail\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                    subjectName\n                    subjectThumbnail\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }"): (typeof documents)["\n    query complaintsByAuthorIdOrReceiverIdQuery($id: String!){\n        complaintsByAuthorOrReceiverId(id:$id){\n            id\n            author{\n                id\n                subjectName\n                subjectThumbnail\n            }\n            receiver{\n                id\n                subjectName\n                subjectThumbnail\n            }\n            status\n            title\n            description\n            createdAt\n            updatedAt\n            replies{\n                id\n                complaintId\n                sender{\n                    id\n                    subjectName\n                    subjectThumbnail\n                }\n                body\n                readAt\n                createdAt\n                updatedAt\n            }\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query complaintsInfoQuery($id: String!) {\n        complaintsInfo(id: $id) {\n            received {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n            resolved {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n            reviewed {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n            sent {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n        }\n    }"): (typeof documents)["\n    query complaintsInfoQuery($id: String!) {\n        complaintsInfo(id: $id) {\n            received {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n            resolved {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n            reviewed {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n            sent {\n                id\n                ownerId\n                complaintId\n                occurredOn\n                dataType\n            }\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query Countries{\n        countries{\n            id\n            name\n            phoneCode\n        }\n    }"): (typeof documents)["\n    query Countries{\n        countries{\n            id\n            name\n            phoneCode\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query CountryStatesQuery($id: Int!){\n        countryStates(id: $id) {\n            id\n            name\n        }\n    }"): (typeof documents)["\n    query CountryStatesQuery($id: Int!){\n        countryStates(id: $id) {\n            id\n            name\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query enterpriseByNameQuery($name: String!){\n        enterpriseByName(name:$name){\n            name\n            logoImg\n            bannerImg\n            website\n            email\n            phoneNumber\n            address {\n                country\n                countryState\n                city\n                }\n            industry\n            foundationDate\n            ownerId\n            employees {\n                id\n                enterpriseId\n                userId\n                user{\n                    userName\n                    person{\n                        profileImg\n                        email\n                        firstName\n                        lastName\n                        genre\n                        pronoun\n                        age\n                        phoneNumber\n                        address{\n                            country\n                            countryState\n                            city\n                        }\n                    }\n                    status\n                }\n                hiringDate\n                approvedHiring\n                approvedHiringAt\n                enterprisePosition\n            }\n        }\n    }"): (typeof documents)["\n    query enterpriseByNameQuery($name: String!){\n        enterpriseByName(name:$name){\n            name\n            logoImg\n            bannerImg\n            website\n            email\n            phoneNumber\n            address {\n                country\n                countryState\n                city\n                }\n            industry\n            foundationDate\n            ownerId\n            employees {\n                id\n                enterpriseId\n                userId\n                user{\n                    userName\n                    person{\n                        profileImg\n                        email\n                        firstName\n                        lastName\n                        genre\n                        pronoun\n                        age\n                        phoneNumber\n                        address{\n                            country\n                            countryState\n                            city\n                        }\n                    }\n                    status\n                }\n                hiringDate\n                approvedHiring\n                approvedHiringAt\n                enterprisePosition\n            }\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\nquery EnterprisesByAuthenticatedUserQuery{\n    enterprisesByAuthenticatedUser{\n        enterprises{\n            authority{\n            authority\n            enterpriseId\n        }\n        enterprise{\n            name\n            logoImg\n            bannerImg\n            website\n            email\n            phoneNumber\n            address {\n                country\n                countryState\n                city\n                }\n            industry\n            foundationDate\n            ownerId\n        }\n        }\n        offices{\n            authority{\n            authority\n            enterpriseId\n        }\n        enterprise{\n            name\n            logoImg\n            bannerImg\n            website\n            email\n            phoneNumber\n            address {\n                country\n                countryState\n                city\n                }\n            industry\n            foundationDate\n            ownerId\n        }\n        }\n    }\n}\n"): (typeof documents)["\nquery EnterprisesByAuthenticatedUserQuery{\n    enterprisesByAuthenticatedUser{\n        enterprises{\n            authority{\n            authority\n            enterpriseId\n        }\n        enterprise{\n            name\n            logoImg\n            bannerImg\n            website\n            email\n            phoneNumber\n            address {\n                country\n                countryState\n                city\n                }\n            industry\n            foundationDate\n            ownerId\n        }\n        }\n        offices{\n            authority{\n            authority\n            enterpriseId\n        }\n        enterprise{\n            name\n            logoImg\n            bannerImg\n            website\n            email\n            phoneNumber\n            address {\n                country\n                countryState\n                city\n                }\n            industry\n            foundationDate\n            ownerId\n        }\n        }\n    }\n}\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query hiringInvitationsByAuthenticatedUserQuery{\n        hiringInvitationsByAuthenticatedUser{\n            eventId\n            enterpriseId\n            proposedPosition\n            ownerId\n            fullName\n            enterpriseEmail\n            enterprisePhone\n            enterpriseLogoImg\n            occurredOn\n            seen\n            status\n            reason\n        }\n    }"): (typeof documents)["\n    query hiringInvitationsByAuthenticatedUserQuery{\n        hiringInvitationsByAuthenticatedUser{\n            eventId\n            enterpriseId\n            proposedPosition\n            ownerId\n            fullName\n            enterpriseEmail\n            enterprisePhone\n            enterpriseLogoImg\n            occurredOn\n            seen\n            status\n            reason\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query industries{\n        industries{\n            id\n            name\n        }\n    }"): (typeof documents)["query industries{\n        industries{\n            id\n            name\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query recipientsByNameLikeQuery($term:String!){\n        recipientsByNameLike(term:$term){\n            id\n            subjectName\n            subjectThumbnail\n            isEnterprise\n        }\n    }\n"): (typeof documents)["\n    query recipientsByNameLikeQuery($term:String!){\n        recipientsByNameLike(term:$term){\n            id\n            subjectName\n            subjectThumbnail\n            isEnterprise\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query User($id:String!){\n        userById(id:$id){\n                userName\n                person {\n                    profileImg\n                    email\n                    firstName\n                    lastName\n                    genre\n                    pronoun\n                    age\n                    phoneNumber\n                    address { \n                        country\n                        countryState\n                        city\n                        }\n                }\n                status\n        }\n    }"): (typeof documents)["\n    query User($id:String!){\n        userById(id:$id){\n                userName\n                person {\n                    profileImg\n                    email\n                    firstName\n                    lastName\n                    genre\n                    pronoun\n                    age\n                    phoneNumber\n                    address { \n                        country\n                        countryState\n                        city\n                        }\n                }\n                status\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query UserDescriptor{\n        userDescriptor{\n            id\n            userName\n            fullName\n            profileImg\n            genre\n            pronoun\n            authorities{\n                enterpriseId\n                principal\n                authority\n            }\n        }\n    }"): (typeof documents)["\n    query UserDescriptor{\n        userDescriptor{\n            id\n            userName\n            fullName\n            profileImg\n            genre\n            pronoun\n            authorities{\n                enterpriseId\n                principal\n                authority\n            }\n        }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query usersForHiringQuery($input: SearchWithPagination!) {\n        usersForHiring(input:$input){\n            users {\n                userName\n                person {\n                    profileImg\n                    email\n                    firstName\n                    lastName\n                    genre\n                    pronoun\n                    age\n                    phoneNumber\n                    address { country countryState city}\n                }\n                status\n            }\n            count\n            limit\n            offset\n            nextCursor\n            prevCursor\n        }\n    }"): (typeof documents)["\n    query usersForHiringQuery($input: SearchWithPagination!) {\n        usersForHiring(input:$input){\n            users {\n                userName\n                person {\n                    profileImg\n                    email\n                    firstName\n                    lastName\n                    genre\n                    pronoun\n                    age\n                    phoneNumber\n                    address { country countryState city}\n                }\n                status\n            }\n            count\n            limit\n            offset\n            nextCursor\n            prevCursor\n        }\n    }"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;